
//import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
     int n;
    String cities[];
    int adjMatrix[][];
    
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        save3 = new javax.swing.JLabel();
        save2 = new javax.swing.JLabel();
        save1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        NO_cities = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name_city = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(969, 547));
        setMinimumSize(new java.awt.Dimension(969, 547));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(970, 547));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("                     Please Wait...");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 290, 120));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSpinner1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSpinner1MouseReleased(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source", "Destination", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 640, 260));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 670, 50));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 191, 33));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 940, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Set Rows");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 80, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("[Press Enter]");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Source, Destination and Distance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 630, 30));

        save3.setBackground(new java.awt.Color(0, 0, 0));
        save3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save3.setForeground(new java.awt.Color(255, 255, 255));
        save3.setText("           Reset");
        save3.setOpaque(true);
        save3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                save3MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save3MouseEntered(evt);
            }
        });
        getContentPane().add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 100, 40));

        save2.setBackground(new java.awt.Color(0, 0, 0));
        save2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save2.setForeground(new java.awt.Color(255, 255, 255));
        save2.setText("   Generate Graph");
        save2.setOpaque(true);
        save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                save2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                save2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save2MouseEntered(evt);
            }
        });
        getContentPane().add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 110, 40));

        save1.setBackground(new java.awt.Color(0, 0, 0));
        save1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save1.setForeground(new java.awt.Color(255, 255, 255));
        save1.setText("        Print Table");
        save1.setOpaque(true);
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save1MouseExited(evt);
            }
        });
        getContentPane().add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 50, 50));

        num.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 20));

        NO_cities.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NO_cities.setForeground(new java.awt.Color(255, 255, 255));
        NO_cities.setText("Number of cities");
        getContentPane().add(NO_cities, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 20));

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("            Result");
        save.setOpaque(true);
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 110, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 960, 70));

        jLabel9.setBackground(new java.awt.Color(30, 33, 56));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cube_field_3d_hd_resolution_by_h1s0ka-d3kqjzk_1.png"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 970, 420));

        name_city.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name_city.setForeground(new java.awt.Color(255, 255, 255));
        name_city.setText("Name of cities");
        getContentPane().add(name_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 110, -1));

        c.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 370, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titlebar.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 970, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
n = Integer.parseInt(num.getText());
jLabel7.setVisible(true);
cities = new String[n];
String p="";
int i;
for(i=0; i<n; i++)
{
    String x = JOptionPane.showInputDialog(null, "City"+(i+1));
    if(x==null)
        break;
    cities[i]=x;
    if(i<n-1)
    p = p+x+", ";
}
if(i==n)
{
    jLabel7.setText("Entered cities : "+p+cities[n-1]);
   // AnimationClass a = new AnimationClass();
   // a.jLabelXLeft(930, 290, 10, 2, jLabel7);
    jLabel8.setText("");
    adjMatrix = new int[n][n];
    for(i=0; i<n; i++)
        for(int j=0; j<n; j++)
             adjMatrix[i][j]=0;        // TODO add your handling code here:
}
    }//GEN-LAST:event_numActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
n = Integer.parseInt(num.getText());
cities = new String[n];
String x = c.getText();
cities = x.split("\\, ");
adjMatrix = new int[n][n];
for(int i=0; i<n; i++)
    for(int j=0; j<n; j++)
        adjMatrix[i][j]=0;        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
save.setBackground(Color.BLUE.brighter().brighter().brighter());        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
save.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       MainPage.this.setVisible(false);

        new NewJFrame().setVisible(true);
         
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jLabel10.setVisible(false);
this.setLocationRelativeTo(null);
//DefaultTableModel m= (DefaultTableModel) jTable1.getModel();
//m.setRowCount(0);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
jLabel5.setText("Minimum Distance Between All Possible Pair of Cities");
        
        jScrollPane1.setVisible(true);
DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
m.setRowCount(0);
ShortestPath sp = new ShortestPath();
int i, max=-1, src=0;
int dist[] = new int[n];

for(i=0; i<n; i++)
{
    int x = sp.dijkstra(adjMatrix, i, n, dist);
    if(x>max)
    {
        max=x;
        src = i;
    }
    m.addRow(new Object[]{cities[i], "", ""});
    for(int j=0; j<n; j++)
    {
        if(j==i)
            continue;
        m.addRow(new Object[]{"", cities[j], dist[j]});
    }
}
max=-1;
int dest=0;
int x = sp.dijkstra(adjMatrix, src, n, dist);
for(i=0; i<n; i++)
    if(max<dist[i])
    {
        max=dist[i];
        dest=i;
    }
jLabel6.setText("Maximum of all the shortest distances : From "+cities[src]+" to "+cities[dest]+" = "+max+"km");
    }//GEN-LAST:event_saveMouseClicked

    private void save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseClicked
         try {
             jTable1.print();        // TODO add your handling code here:
         } catch (PrinterException ex) {
             Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_save1MouseClicked

    private void save1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseEntered
save1.setBackground(Color.BLUE.brighter().brighter());        // TODO add your handling code here:
    }//GEN-LAST:event_save1MouseEntered

    private void save1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseExited
save1.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_save1MouseExited

    private void save2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseClicked

    private void save2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseEntered
save2.setBackground(Color.BLUE.brighter());      // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseEntered

    private void save2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseExited
save2.setBackground(Color.BLACK);      // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseExited

    private void save3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseClicked
jLabel7.setText("");
jLabel8.setText("[Press Enter]");
jLabel7.setLocation(930, 140);
jLabel5.setText("Enter Source, Destination and Distance");
jLabel6.setText("");
jScrollPane1.setVisible(true);
num.setText("");
c.setText("");
jSpinner1.setValue(0);
DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
model1.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseClicked

    private void save3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseEntered
save3.setBackground(Color.BLUE.brighter());      // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseEntered

    private void save3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseExited
 save3.setBackground(Color.black);      // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseExited

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
m.setRowCount(Integer.parseInt(jSpinner1.getValue().toString()));
jTable1.setModel(m);// TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jSpinner1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MousePressed
DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
m.setRowCount(Integer.parseInt(jSpinner1.getValue().toString()));
jTable1.setModel(m);        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MousePressed

    private void jSpinner1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseReleased
DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
m.setRowCount(Integer.parseInt(jSpinner1.getValue().toString()));
jTable1.setModel(m);        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseReleased

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
if(Integer.parseInt(jSpinner1.getValue().toString())<0)
{
    jSpinner1.setValue(0);
}
else
{
    m.setRowCount(Integer.parseInt(jSpinner1.getValue().toString()));
    jTable1.setModel(m);        // TODO add your handling code here:
}
    }//GEN-LAST:event_jSpinner1StateChanged

    private void save3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseReleased

    private void save2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseReleased
  long startTime = System.currentTimeMillis();
long elapsedTime = 0L;
while (elapsedTime < 3000)
{
    
    elapsedTime = System.currentTimeMillis()-startTime;
}
jLabel10.setVisible(false);
int i, j, dist;
String src, dest;
//src = source.getText();
//dest = des.getText();
//dist = Integer.parseInt(dis.getText());
int row=0, count = jTable1.getRowCount();
while(count!=0)
{
    src = (String) jTable1.getValueAt(row, 0);
    //System.out.println(src);
    dest = (String) jTable1.getValueAt(row, 1);
    //System.out.println(dest);
    dist = Integer.parseInt(jTable1.getValueAt(row, 2).toString());
    //System.out.println(dist);
    for(i=0; i<n; i++)
    {
     if(cities[i].equals(src))
        break;
    }
    for(j=0; j<n; j++)
    {
     if(cities[j].equals(dest))
        break;
    }
    System.out.println(i+" "+j);
    adjMatrix[i][j]=adjMatrix[j][i]=dist;
    row++;
    count--;
}
for(i=0; i<n; i++)
{
    for(j=0; j<n; j++)
        System.out.print(adjMatrix[i][j]+" ");
    System.out.println();
}

  
         // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseReleased

    private void save2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MousePressed
jLabel7.setVisible(false);
        jLabel10.setVisible(true);  
             // TODO add your handling code here:
    }//GEN-LAST:event_save2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NO_cities;
    private javax.swing.JTextField c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name_city;
    private javax.swing.JTextField num;
    private javax.swing.JLabel save;
    private javax.swing.JLabel save1;
    private javax.swing.JLabel save2;
    private javax.swing.JLabel save3;
    // End of variables declaration//GEN-END:variables
}
